# Generated by Django 3.2.9 on 2022-07-09 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorturl', '0002_shorturl_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='clicks',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
